### PR TITLE
feat: add remove, remove_first string filters

### LINKED ISSUE #3: Add remove function
See here for `remove` function

https://help.shopify.com/en/themes/liquid/filters/string-filters#remove
And 
https://help.shopify.com/en/themes/liquid/filters/string-filters#remove_first

### PR DESCRIPTION
**Pull request by distributedlock**
Added `remove` and `remove_first` filters.

Resolves #3.

### CODE REVIEW

**Comment by distributedlock** [comment]
Also, I got rid of trailing whitespace and misalignment. Formatted per [prettier](https://prettier.io/)'s whitespace standards.

**Comment by mazipan** [comment]
Conflict ya

**Comment by distributedlock** [comment]
@mazipan Resolved merge conflicts.

**Comment by distributedlock** [comment]
@mazipan Ok, merge conflicts resolved.

**Comment by mazipan** [comment]
Still conflict

**Comment by distributedlock** [comment]
@mazipan Resolved again.

**Review by mazipan — CHANGES_REQUESTED** [review]
Fix all conflict first ya

**Comment by distributedlock** [comment]
@mazipan Yes, it is resolved in my latest commit.

**Comment by mazipan** [comment]
Please add demo and unit test in other PR ya

**Pull request merged**
